shellEmulator: true

trustPolicy: no-downgrade
packages: []

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.15
    '@vitejs/plugin-vue': ^6.0.3
    jsdom: ^27.4.0
    unocss: ^66.5.12
    unplugin: ^2.3.5
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@types/node': ^25.0.3
    '@unocss/eslint-plugin': ^66.5.12
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    eslint: ^9.39.2
    eslint-plugin-format: ^1.2.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vitest: ^4.0.16
    vue-tsc: ^3.2.2
  frontend:
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: ^3.5.26
    vue-router: ^4.6.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
